AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "yt-dlp --dump-json. Specific options."
Resources:
  YtDmpFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: ./x.zip
      Runtime: "python3.9"
      Handler: "app.lambda_handler"
      MemorySize: 128
      Timeout: 30
      Events:
        YtDmpApi:
          Type: "Api"
          Properties:
            Path: "/{proxy+}"
            Method: "GET"
#
# Outputs:
#   YtDmpApiUrl:
#     Description: "API Gateway endpoint URL for yt-dlp info."
#     Value: !Sub "https://${YtDmpApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/{proxy+}"
